### ISSUE TITLE
CMAC - Different results when using buffer chunks

### ISSUE THREAD

**Issue by djaeckle** [BrianGladman/modes#1]
The issue is about the CMAC algorithm implementation.

I get different results when I call `cmac_data` several times with chunks of the input buffer instead of calling `cmac_data` only once with the complete buffer.

In my two use cases, the size of the input buffer is 112 bytes. 
- In the first case, I call `cmac_data` with the buffer size of 112. 

- In the second case, I call `cmac_data` with the first 80 bytes and afterwards with the remaining 32 bytes.

After calling `cmac_end`, the results are different. The issue only occurs, when the first chunk is a multiple of 16 bytes.

I guess the issue is that in the second case and in the second call of `cmac_data`, we are running into the while loop:
```
while(cnt < len && b_pos < BLOCK_SIZE)
            UI8_PTR(ctx->txt_cbc)[b_pos++] ^= buf[cnt++];
```
I think when `ctx->txt_cnt` is a multiple of `BLOCK_SIZE`, we shouldn't execute the code part. If I add the following code snippet at the beginning of the function, I get the same results for both use cases:
```
    if(((ctx->txt_cnt % BLOCK_SIZE) == 0) && (ctx->txt_cnt > 0))
      b_pos = BLOCK_SIZE;
    else
      b_pos = ctx->txt_cnt & BLK_ADR_MASK;
```

**Comment by BrianGladman** [comment]
Thank you for reporting this issue which affects both CMAC and OMAC.  I have corrected the code but I have not tested the correction as I am away from my development machine at the moment. I will do so as soon as possible.

**Comment by djaeckle** [comment]
Thank you very much for the quick response.

**Comment by BrianGladman** [comment]
That fix I did is wrong. I will look at this when I get back to my development machine.

**Comment by BrianGladman** [comment]
Your fix is correct. I have now useed it to correcct the bug in both CMAC and OMAC.

Thank you for picking it up

**Comment by djaeckle** [comment]
Thanks for the feedback.
